/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AltaAlumno: typeof import('./src/components/AltaAlumno.vue')['default']
    AltaAsignatura: typeof import('./src/components/AltaAsignatura.vue')['default']
    AltaAsignaturaProfesor: typeof import('./src/components/AltaAsignaturaProfesor.vue')['default']
    AltaProfesor: typeof import('./src/components/AltaProfesor.vue')['default']
    AltaUsuario: typeof import('./src/components/AltaUsuario.vue')['default']
    Alumno: typeof import('./src/components/Alumno.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BuscadorAlumno: typeof import('./src/components/BuscadorAlumno.vue')['default']
    'ElementosBorrados*****': typeof import('./src/components/ElementosBorrados*****.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LightDarkSwtichBtn: typeof import('./src/components/Layouts/LightDarkSwtichBtn.vue')['default']
    ListadoAlumnos: typeof import('./src/components/ListadoAlumnos.vue')['default']
    ListadoAsignaturasProfesores: typeof import('./src/components/ListadoAsignaturasProfesores.vue')['default']
    ListadoMatriculas: typeof import('./src/components/ListadoMatriculas.vue')['default']
    ListadoProfesores: typeof import('./src/components/ListadoProfesores.vue')['default']
    ListadoUsuarios: typeof import('./src/components/ListadoUsuarios.vue')['default']
    LoginUser: typeof import('./src/components/LoginUser.vue')['default']
    LoginUser_VIEJO: typeof import('./src/components/LoginUser_VIEJO.vue')['default']
    MainFooter: typeof import('./src/components/Layouts/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/Layouts/MainHeader.vue')['default']
    MainSidebar: typeof import('./src/components/Layouts/MainSidebar.vue')['default']
    Matricula: typeof import('./src/components/Matricula.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    Portal: (typeof import('portal-vue'))['Portal']
    PortalTarget: (typeof import('portal-vue'))['PortalTarget']
    Profesor: typeof import('./src/components/Profesor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Usuario: typeof import('./src/components/Usuario.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
